#!/usr/bin/env bash

if [[ $UID -ne 0 ]]
then
	echo "Denne kommando skal køres som root"
	exit 1
fi

# Setup the OS2BorgerPC client on an Ubuntu Server

DIR=$(dirname ${BASH_SOURCE[0]})

# Avoid script stopping because it wants user input
export DEBIAN_FRONTEND=noninteractive

# Set proper, restricted permissions on superuser homedir
chmod -R 700 /home/superuser

# Install all necessary packages and dependencies
$DIR/install_dependencies.sh

# Prepare to run jobs
mkdir -p /var/lib/os2borgerpc/jobs
chmod -R og-r /var/lib/os2borgerpc

# Prepare to run security events
mkdir -p /etc/os2borgerpc/security/

# Set product in configuration
PRODUCT="os2borgerpc kiosk"
echo "os2_product: $PRODUCT" >> /etc/os2borgerpc/os2borgerpc.conf

# Set version in configuration
VERSION=$(cat "$DIR"/VERSION)
echo "os2borgerpc_version: $VERSION" >> /etc/os2borgerpc/os2borgerpc.conf

# Insert values from config.cfg that are prefixed with 'DEFAULT_' into os2borgerpc.conf.
# Path to the configuration file
CONFIG_FILE="$DIR/config.cfg"

# Read each line in the configuration file and reformat it
while IFS='=' read -r key value; do
    # Skip empty lines, lines without '=', and lines starting with '#'
    if [[ -n "$key" && -n "$value" && "$key" != \#* ]]; then
        # Convert key to lowercase and remove "DEFAULT_" prefix
        lowercase_key=$(echo "$key" | sed 's/^DEFAULT_//' | tr '[:upper:]' '[:lower:]')
        
        # Write in "key: value" format
        echo "${lowercase_key}: ${value}" >> /etc/os2borgerpc/os2borgerpc.conf
    fi
done < "$CONFIG_FILE"

# Setup Chromium user
USER="chrome"
if ! id $USER &>/dev/null; then
  useradd $USER -m -p 12345 -s /bin/bash -U
fi

# Setup autologin of default user
mkdir -p /etc/systemd/system/getty@tty1.service.d

# Note: The empty ExecStart is not insignificant!
# By default the value is appended, so the empty line changes it to an override
cat << EOF > /etc/systemd/system/getty@tty1.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --noissue --autologin $USER %I $TERM
Type=idle
EOF

# Create script to rotate screen
mkdir --parents /usr/share/os2borgerpc/bin
cat << EOF > /usr/share/os2borgerpc/bin/rotate_screen.sh
#!/usr/bin/env sh

set -x

TIME=\$1
ORIENTATION=\$2

sleep \$TIME

export XAUTHORITY=/home/$USER/.Xauthority

# --listactivemonitors lists the primary monitor first
ALL_MONITORS=\$(xrandr --listactivemonitors | tail -n +2 | cut --delimiter ' ' --fields 6)

# Make all connected monitors display what the first monitor displays, rather than them extending the desktop
PRIMARY_MONITOR=\$(echo "\$ALL_MONITORS" | head -n 1)
OTHER_MONITORS=\$(echo "\$ALL_MONITORS" | tail -n +2)
echo "\$OTHER_MONITORS" | xargs -I {} xrandr --output {} --same-as "\$PRIMARY_MONITOR"

# Rotate screen - and if more than one monitor, rotate them all.
echo "\$ALL_MONITORS" | xargs -I {} xrandr --output {} --rotate \$ORIENTATION
EOF

chmod +x /usr/share/os2borgerpc/bin/rotate_screen.sh

# Fix dpkg settings
cat << EOF > /etc/apt/apt.conf.d/local
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};
Dpkg::Lock {Timeout "300";};
EOF

#  Connect to the admin system
update_client_and_register.sh
