#!/usr/bin/env bash

# Setup the OS2BorgerPC client on an Ubuntu Server

DIR=$(dirname ${BASH_SOURCE[0]})

# Avoid script stopping because it wants user input.
export DEBIAN_FRONTEND=noninteractive

# Install all necessary packages and dependencies
$DIR/install_dependencies.sh

# Prepare to run jobs
mkdir -p /var/lib/os2borgerpc/jobs
chmod -R og-r /var/lib/os2borgerpc

# Prepare to run security events
SECURITY_DIR=/etc/os2borgerpc/security/
mkdir -p $SECURITY_DIR
cp -R "${DIR}/security/*" "$SECURITY_DIR"

# Set version in configuration
VERSION=$(cat "$DIR"/../../VERSION)
set_os2borgerpc_config os2borgerpc_version "$VERSION"

#  Connect to the admin system

register_new_os2borgerpc_client.sh
